### ISSUE TITLE
Compile failure with base < 4.6

### ISSUE THREAD

**Issue by hvr** [josefs/STMonadTrans#13]
```
$ cabal new-build -w ghc-7.4.2
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - STMonadTrans-0.4.3 {STMonadTrans-0.4.3-inplace} (lib) (first run)
Configuring library for STMonadTrans-0.4.3..
Preprocessing library for STMonadTrans-0.4.3..
Building library for STMonadTrans-0.4.3..

Control/Monad/ST/Trans.hs:2:50:
    Warning: -XRecursiveDo is deprecated: use -XDoRec or pragma {-# LANGUAGE DoRec #-} instead

Control/Monad/ST/Trans/Internal.hs:2:50:
    Warning: -XRecursiveDo is deprecated: use -XDoRec or pragma {-# LANGUAGE DoRec #-} instead
[1 of 2] Compiling Control.Monad.ST.Trans.Internal ( Control/Monad/ST/Trans/Internal.hs, /tmp/STMonadTrans-0.4.3/dist-newstyle/build/x86_64-linux/ghc-7.4.2/STMonadTrans-0.4.3/build/Control/Monad/ST/Trans/Internal.o )

Control/Monad/ST/Trans/Internal.hs:172:58:
    Not in scope: type constructor or class `Word'
    Perhaps you meant one of these:
      `Word#' (imported from GHC.Base), `Word8' (imported from GHC.Word)
```

**Comment by hvr** [comment]
I've already performed the necessary revisions on Hackage to keep the solver from picking up bad install-plans (NB: 0.4.2/.1 required a tighter lower bound `base >= 4.7`, while 0.4 required `base >= 4.8`).

 - https://hackage.haskell.org/package/STMonadTrans-0.4.3/revisions
 - https://hackage.haskell.org/package/STMonadTrans-0.4.2/revisions
 - https://hackage.haskell.org/package/STMonadTrans-0.4.1/revisions
 - https://hackage.haskell.org/package/STMonadTrans-0.4/revisions

Please make sure that the next release of `STMonadTrans` either restores compatibility with older `base` versions or alternatively declares accurate bounds.

See also https://matrix.hackage.haskell.org/package/STMonadTrans for an overview

**Comment by andreasabel** [comment]
Thanks @hvr.
STMonadTrans builds with 7.6-8.10 as of today: https://github.com/josefs/STMonadTrans/actions/runs/446969248
